### ISSUE TITLE
后台登陆一直提示不正确

### ISSUE THREAD

**Issue by carolcoral** [unilei/aipan-netdisk-search#3]
账号和密码都是对的，但是后台登陆一直提示不正确无法登录
<img width="1331" alt="image" src="https://github.com/user-attachments/assets/7c883eb2-cdf8-4a47-8c5c-875ca0d7a301" />

**Comment by mr-dragon** [comment]
好像表没有初始化，我也是

**Comment by carolcoral** [comment]
> 好像表没有初始化，我也是

我看代码还做了多次hash，也不方便手动直接插入数据到表

**Comment by unilei** [comment]
https://www.aipan.me/blog/%E5%A6%82%E4%BD%95%E9%83%A8%E7%BD%B2%E5%92%8Caipanme-%E5%90%8C%E6%A0%B7%E7%9A%84%E7%BD%91%E7%AB%99-5-1734676015648

不好意思，最近没时间管理这个项目，你看下部署的脚本，很简单，研究下

**Comment by telnetpig** [comment]
https://blog.csdn.net/wbsu2004/article/details/144223293
参考这个教程和镜像

**Comment by jiangxingxiao** [comment]
> https://www.aipan.me/blog/%E5%A6%82%E4%BD%95%E9%83%A8%E7%BD%B2%E5%92%8Caipanme-%E5%90%8C%E6%A0%B7%E7%9A%84%E7%BD%91%E7%AB%99-5-1734676015648
> 
> 不好意思，最近没时间管理这个项目，你看下部署的脚本，很简单，研究下

大佬能不能给前端页面添加一个登陆界面，防止被扫到。然后直播源大部分都挂掉了，能否在前端或者后台添加自定义添加直播源之类的。当然，这只是个人的小小建议，一切以作者为准，感谢作者的开源项目，感谢

**Comment by carolcoral** [comment]
@unilei 佬，试了下改compose的环境变量，加上了`NUXT`相关参数，也执行了`npx prisma migrate deploy`还是不太行，能否麻烦帮忙参考下怎么处理呢，我用的docker compose方式部署，没有填写本地`.env`文件，直接用的环境变量

```yaml
version: "3.8"

services:
  aipan-netdisk-search:
    image: unilei/aipan-netdisk-search:latest # 如果你想从 Docker Hub 获取镜像，可以使用这一行
    container_name: aipan-netdisk-search-app
    restart: always # 确保容器在停止后自动重启
    build:
      context: ./aipan-netdisk-search/ # 构建上下文，通常是 Dockerfile 所在的目录
      dockerfile: Dockerfile # Dockerfile 的名称
      args:
        ADMIN_USER: ${ADMIN_USER}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        JWT_SECRET: ${JWT_SECRET}
        DATABASE_URL: ${DATABASE_URL}
        DATABASE_SCHEMA: ${DATABASE_SCHEMA}
        SHADOW_DATABASE_URL: ${SHADOW_DATABASE_URL}
    ports:
      - "3000:3000" # 映射容器的 3000 端口到宿主机的 3000 端口
    environment:
      - ADMIN_USER=username
      - ADMIN_PASSWORD=password
      - ADMIN_EMAIL=admin@admin.com
      - JWT_SECRET=mb78h@67f!
      - DATABASE_SCHEMA=public
      - DATABASE_URL=postgresql://aipan:openpostgresql@aipan-search-db:5432/aipan
      - SHADOW_DATABASE_URL=postgresql://aipan:openpostgresql@aipan-search-db:5432/aipan
      - NODE_ENV=${NODE_ENV:-production}
      - NUXT_ADMIN_USER=${ADMIN_USER}
      - NUXT_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - NUXT_ADMIN_EMAIL=${ADMIN_EMAIL}
      - NUXT_JWT_SECRET=${JWT_SECRET}
      - NUXT_DATABASE_SCHEMA=${DATABASE_SCHEMA}
      - NUXT_DATABASE_URL=${DATABASE_URL}
      #- NUXT_PUBLIC_GITHUB_OWNER=${NUXT_PUBLIC_GITHUB_OWNER}
      #- NUXT_PUBLIC_GITHUB_REPO=${NUXT_PUBLIC_GITHUB_REPO}
      #- NUXT_PUBLIC_GITHUB_TOKEN=${NUXT_PUBLIC_GITHUB_TOKEN}
      #- NUXT_PUBLIC_GITHUB_BRANCH=${NUXT_PUBLIC_GITHUB_BRANCH}
      # GitHub 配置
      # GitHub 用户名
      # - NUXT_PUBLIC_GITHUB_OWNER=
      # 用于存储图片的仓库名称
      # - NUXT_PUBLIC_GITHUB_REPO=
      # GitHub Personal Access Token
      # - NUXT_PUBLIC_GITHUB_TOKEN=ghp_  # 替换为新生成的 token
      # 默认分支名称
      # - NUXT_PUBLIC_GITHUB_BRANCH=
    # networks:
    #   aipan_search_network:
    network_mode: "bridge"
      
  aipan-search-db:
    image: postgres:15.4
    restart: on-failure:3
    # networks:
    #   aipan_search_network:
    network_mode: "bridge"
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=openpostgresql
      - POSTGRES_USER=aipan
      - POSTGRES_DB=aipan
      - PGUSER=aipan

# networks:
#   aipan_search_network:
#     driver: bridge
```

**Comment by jiangxingxiao** [comment]
你该搞定了吗？我也不行，而且最重要音乐也没法用，你能搜音乐吗？

**Comment by carolcoral** [comment]
> 你该搞定了吗？我也不行，而且最重要音乐也没法用，你能搜音乐吗？

音乐用不了

**Comment by carolcoral** [comment]
目前已知：

**Comment by carolcoral** [comment]
4. 搜索过程中页面大小会不停改变
<img width="1508" alt="image" src="https://github.com/user-attachments/assets/32a31589-1af9-4a44-99c2-bf5efe6fc6fe" />

请作者什么时候有空了在处理吧，以上内容仅做记录📝

**Comment by jiangxingxiao** [comment]
> **目前已知：**
> 1. 后台登陆无法成功，一直提示账号/密码不正确
> 2. 音乐页面无内容
> 3. 电视TV页面无法切换`m3u`源（内置的直播源基本不能用了）

严重怀疑我们俩问题一模一样

**Comment by carolcoral** [comment]
> > **目前已知：**
> > 
> > 1. 后台登陆无法成功，一直提示账号/密码不正确
> > 2. 音乐页面无内容
> > 3. 电视TV页面无法切换`m3u`源（内置的直播源基本不能用了）
> 
> 严重怀疑我们俩问题一模一样

因为这个版本的问题都是这些。。。

**Comment by jiangxingxiao** [comment]
我找到一个部署成功的，但是看不太懂，博主博客也没法留言，你研究下，可以了更我说声教教我
https://laosu.tech/2024/12/03/%E7%BD%91%E7%9B%98%E8%81%9A%E5%90%88%E6%90%9C%E7%B4%A2%E9%A1%B9%E7%9B%AEAipan%EF%BC%88%E7%88%B1%E7%9B%BC%EF%BC%89%E3%80%90%E7%BB%AD%E3%80%91/?highlight=%E7%88%B1

**Comment by carolcoral** [comment]
> 我找到一个部署成功的，但是看不太懂，博主博客也没法留言，你研究下，可以了更我说声教教我 https://laosu.tech/2024/12/03/%E7%BD%91%E7%9B%98%E8%81%9A%E5%90%88%E6%90%9C%E7%B4%A2%E9%A1%B9%E7%9B%AEAipan%EF%BC%88%E7%88%B1%E7%9B%BC%EF%BC%89%E3%80%90%E7%BB%AD%E3%80%91/?highlight=%E7%88%B1

不太行，我用了compose本地编译，没有用这种`start.sh`的方案

**Comment by carolcoral** [comment]
<img width="1291" alt="image" src="https://github.com/user-attachments/assets/8ddde354-23a3-49c9-8bd8-ce02f291f3f7" />
搞定

**Comment by carolcoral** [comment]
本地编译方法：

```yaml
version: "3.8"

services:
  aipan-netdisk-search:
    image: carolcoral/aipan-netdisk-search:1.0.0
    container_name: aipan-netdisk-search-app
    restart: on-failure:3 # 确保容器在停止后自动重启
    build:
      context: ./aipan-netdisk-search/ # 构建上下文，通常是 Dockerfile 所在的目录
      dockerfile: Dockerfile # Dockerfile 的名称
      args:
        ADMIN_USER: ${ADMIN_USER}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        JWT_SECRET: ${JWT_SECRET}
        DATABASE_URL: ${DATABASE_URL}
        DATABASE_SCHEMA: ${DATABASE_SCHEMA}
    ports:
      - "3000:3000" # 映射容器的 3000 端口到宿主机的 3000 端口
    environment:
      ADMIN_USER: ADMIN_USER
      ADMIN_PASSWORD: ADMIN_PASSWORD
      ADMIN_EMAIL: NUXT_ADMIN_EMAIL
      JWT_SECRET: JWT_SECRET
      DATABASE_SCHEMA: DATABASE_SCHEMA
      DATABASE_URL: DATABASE_URL
      SHADOW_DATABASE_URL: DATABASE_URL
      NODE_ENV: dev
      NUXT_ADMIN_USER: NUXT_ADMIN_USER
      NUXT_ADMIN_PASSWORD: NUXT_ADMIN_PASSWORD
      NUXT_ADMIN_EMAIL: NUXT_ADMIN_EMAIL
      NUXT_JWT_SECRET: NUXT_JWT_SECRET
      NUXT_DATABASE_URL: DATABASE_URL
    networks:
      aipan_search_network:
    depends_on:
      - aipan-search-db
    links:
      - aipan-search-db
      
  aipan-search-db:
    container_name: aipan-search-db
    image: postgres:15.4
    restart: on-failure:3
    networks:
      aipan_search_network:
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_DB=POSTGRES_DB
      - PGUSER=PGUSER

networks:
  aipan_search_network:
    driver: bridge

```
