### ISSUE TITLE
使用最新的官方Docker镜像；无法登陆后台（邮箱或密码不正确）

### ISSUE THREAD

**Issue by NJYZ-96** [unilei/aipan-netdisk-search#67]
我确定我输入的邮箱密码都是正确的，但无法进入后台

Docker-Compose 模板文档：（敏感信息用***表示）
```
services:
    AiPan:
        container_name: ${CONTAINER_NAME}
        environment:
            ADMIN_EMAIL: ***@gmail.com
            ADMIN_PASSWORD: ***@aipa
            ADMIN_USER: NJYZ
            DATABASE_SCHEMA: public
            DATABASE_URL: postgresql://aipan:***@PostgreSQL:5432/aipan
            JWT_SECRET: iufgkYFGYYJ46g
        image: unilei/aipan-netdisk-search:latest
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:3000
        restart: always
```

容器日志如下：
```
␛[2K1Panel-AiPan  | Running database migrations...
␛[2K1Panel-AiPan  | Prisma schema loaded from prisma/schema.prisma
␛[2K1Panel-AiPan  | Datasource "db": PostgreSQL database "aipan", schema "public" at "1Panel-PostgreSQL:5432"
␛[2K1Panel-AiPan  | 
␛[2K1Panel-AiPan  | 5 migrations found in prisma/migrations
␛[2K1Panel-AiPan  | 
␛[2K1Panel-AiPan  | Applying migration `20240911070047_init`
␛[2K1Panel-AiPan  | Applying migration `20240911070350_init`
␛[2K1Panel-AiPan  | Applying migration `20240912020148_enable_cascade_delete_for_posts`
␛[2K1Panel-AiPan  | Applying migration `20240912045442_add_slug_to_post`
␛[2K1Panel-AiPan  | Applying migration `20241027063215_add`
␛[2K1Panel-AiPan  | 
␛[2K1Panel-AiPan  | The following migration(s) have been applied:
␛[2K1Panel-AiPan  | 
␛[2K1Panel-AiPan  | migrations/
␛[2K1Panel-AiPan  |   └─ 20240911070047_init/
␛[2K1Panel-AiPan  |     └─ migration.sql
␛[2K1Panel-AiPan  |   └─ 20240911070350_init/
␛[2K1Panel-AiPan  |     └─ migration.sql
␛[2K1Panel-AiPan  |   └─ 20240912020148_enable_cascade_delete_for_posts/
␛[2K1Panel-AiPan  |     └─ migration.sql
␛[2K1Panel-AiPan  |   └─ 20240912045442_add_slug_to_post/
␛[2K1Panel-AiPan  |     └─ migration.sql
␛[2K1Panel-AiPan  |   └─ 20241027063215_add/
␛[2K1Panel-AiPan  |     └─ migration.sql
␛[2K1Panel-AiPan  |       
␛[2K1Panel-AiPan  | All migrations have been successfully applied.
␛[2K1Panel-AiPan  | npm notice
␛[2K1Panel-AiPan  | npm notice New minor version of npm available! 10.7.0 -> 10.9.0
␛[2K1Panel-AiPan  | npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
␛[2K1Panel-AiPan  | npm notice To update run: npm install -g npm@10.9.0
␛[2K1Panel-AiPan  | npm notice
␛[2K1Panel-AiPan  | Starting application...
␛[2K1Panel-AiPan  | Listening on http://[::]:3000
```
