### ISSUE TITLE
很好用的一个程序，可以出个官方的Docker-Compose文件吗？

### ISSUE THREAD

**Issue by 8080713** [unilei/aipan-netdisk-search#74]
按照教程搭建，后台无法登录，提示密码错误
[nuxt] [request error] [unhandled] [500] 

Invalid `prisma.alist.count()` invocation:

getaddrinfo ENOTFOUND postgres

**Comment by rangerzhou** [comment]
```
version: '3.9'
services:
  netdisksearch:
    image: xxx/aipan-netdisk-search:latest
    container_name: aipan-netdisk-search
    network_mode: bridge
    restart: always
    ports:
        - 3000:3000
    logging:
        options:
            max-size: "5m"
            max-file: "5"
    environment:
      - ADMIN_USER="user"
      - ADMIN_PASSWORD="password"
      - ADMIN_EMAIL="xxx@xxx.com"
      - JWT_SECRET="xxxxx"
      - DATABASE_SCHEMA="public"
      - DATABASE_URL="xxx"
      - SHADOW_DATABASE_URL="" # 留空即可
```
